version: '3.7'

services:
  config-server:
    expose:
        - 9000
    build:
      context: config-server
      dockerfile: server.dockerfile
    ports:
      - 9000:9000
    depends_on:
      - zookeeper
    environment:
      - ZK_URI=zookeeper:2181
    networks:
       - network1
  book:
    expose:
      - 8090
    build:
      context: book
      dockerfile: book.dockerfile
    ports:
      - 8090:8090
    depends_on:
      - config-server
      - zookeeper
    environment:
      - ZK_URI=zookeeper:2181
      - ZIPKIN_URI=http://zipkin:9411
    networks:
      - network1
  order:
    expose:
      - 8070
    build:
      context: order
      dockerfile: order.dockerfile
    ports:
      - 8070:8070
    depends_on:
      - config-server
      - zookeeper
    environment:
      - ZK_URI=zookeeper:2181
    networks:
      - network1
  statistics:
    expose:
      - 8050
    build:
      context: statistics
      dockerfile: statistics.dockerfile
    ports:
      - 8050:8050
    depends_on:
      - zookeeper
    environment:
      - ZK_URI=zookeeper:2181
      - ZIPKIN_URI=http://zipkin:9411
    networks:
      - network1
  gateway:
    expose:
      - 8010
    build:
      context: gateway
      dockerfile: gateway.dockerfile
    ports:
      - 8010:8010
    depends_on:
      - zookeeper
    environment:
      - ZK_URI=zookeeper:2181
    networks:
      - network1
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
    networks:
      - network1
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - network1
networks:
  network1:
    driver: bridge