version: '3.7'

services:
  config-server:
    expose:
        - 9000
    build:
      context: config-server
      dockerfile: server.dockerfile
    ports:
      - 9000:9000
    networks:
       - network1
networks:
  network1:
    driver: bridge