version: '3.7'

services:
  config-server:
    expose:
        - 9000
    build:
      context: config-server
      dockerfile: server.dockerfile
    ports:
      - 9000:9000
    depends_on:
      - eureka-server
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:9010/eureka
    networks:
       - network1
  book:
    expose:
      - 8090
    build:
      context: book
      dockerfile: book.dockerfile
    ports:
      - 8090:8090
    depends_on:
      - config-server
      - eureka-server
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:9010/eureka
    networks:
      - network1
  order:
    expose:
      - 8070
    build:
      context: order
      dockerfile: order.dockerfile
    ports:
      - 8070:8070
    depends_on:
      - config-server
      - eureka-server
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:9010/eureka
    networks:
      - network1
  statistics:
    expose:
      - 8050
    build:
      context: statistics
      dockerfile: statistics.dockerfile
    ports:
      - 8050:8050
    depends_on:
      - eureka-server
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:9010/eureka
    networks:
      - network1
  gateway:
    expose:
      - 8010
    build:
      context: gateway
      dockerfile: gateway.dockerfile
    ports:
      - 8010:8010
    depends_on:
      - eureka-server
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:9010/eureka
    networks:
      - network1
  eureka-server:
    expose:
      - 9010
    build:
      context: eureka-server
      dockerfile: eureka.dockerfile
    ports:
      - 9010:9010
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:9010/eureka
    networks:
      - network1
networks:
  network1:
    driver: bridge