server:
   port: 8010
spring:
   application:
      name: gateway
   cloud:
      zookeeper:
         discovery:
            enabled: true
               register: true
            connect-string: ${ZK_URI:localhost:2181}
      gateway:
         discovery:
            locator:
               enabled: true
               lowerCaseServiceId: true

