server:
   port: 8010
spring:
   application:
      name: library-client
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lowerCaseServiceId: true
