server:
   port: 8010
spring:
   application:
      name: gateway
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lowerCaseServiceId: true

