server:
  port: 8050
spring:
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411}
  application:
    name: statistics
  cloud:
    zookeeper:
      discovery:
        enabled: true
        register: true
      connect-string: ${ZK_URI:localhost:2181}
