#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/it-discovery/config
#          searchPaths:
spring:
  profiles:
    active: native
  cloud:
    zookeeper:
      discovery:
        enabled: true
        register: true
      connect-string: ${ZK_URI:localhost:2181}
